insert into zone (nom) values ('Ecole');
insert into zone (nom) values ('Logements');
INSERT INTO batiment (nom, id_zone) VALUES ('Bat A', 1);
INSERT INTO batiment (nom, id_zone) VALUES ('Bat B', 1);
INSERT INTO batiment (nom, id_zone) VALUES ('Bat C', 1);
INSERT INTO batiment (nom, id_zone) VALUES ('Bat P', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('A1', 1);
INSERT INTO etage (nom, id_batiment) VALUES ('A2', 1);
INSERT INTO etage (nom, id_batiment) VALUES ('A3', 1);
INSERT INTO etage (nom, id_batiment) VALUES ('B1', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('B2', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('B3', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('C-1', 3);
INSERT INTO etage (nom, id_batiment) VALUES ('C0', 3);
INSERT INTO etage (nom, id_batiment) VALUES ('C1', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A100', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A101', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A102', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A103', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A200', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A201', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A202', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A203', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A300', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A301', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A302', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A303', 3);
INSERT INTO piece (nom, id_etage) VALUES ('B100', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B101', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B102', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B103', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B200', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B201', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B202', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B203', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B300', 6);
INSERT INTO piece (nom, id_etage) VALUES ('B301', 6);
INSERT INTO piece (nom, id_etage) VALUES ('B302', 6);
INSERT INTO piece (nom, id_etage) VALUES ('B303', 6);
INSERT INTO piece (nom, id_etage) VALUES ('C-100', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C-101', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C-102', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C-103', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C000', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C001', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C002', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C003', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C100', 9);
INSERT INTO piece (nom, id_etage) VALUES ('C101', 9);
INSERT INTO piece (nom, id_etage) VALUES ('C102', 9);
INSERT INTO piece (nom, id_etage) VALUES ('C103', 9);
INSERT INTO categorie (nom) VALUES ('Chaise');
INSERT INTO categorie (nom) VALUES ('Table');
INSERT INTO categorie (nom) VALUES ('PC portable');
INSERT INTO categorie (nom) VALUES ('Vidéo projecteur');
INSERT INTO etat (nom) VALUES ('Neuf');
INSERT INTO etat (nom) VALUES ('Bon état');
INSERT INTO etat (nom) VALUES ('Mauvais état');
INSERT INTO etat (nom) VALUES ('En attente de destruction');
INSERT INTO etat (nom) VALUES ('Détruit');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00001', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 1', 1234, 'Marque 1');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00002', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 2', 5678, 'Marque 2');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00003', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 3', 9101, 'Marque 3');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00004', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 4', 1112, 'Marque 4');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00005', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 5', 1314, 'Marque 5');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00006', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 6', 1516, 'Marque 6');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00007', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 7', 1718, 'Marque 7');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00008', 1, 5, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 8', 1920, 'Marque 8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00009', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 9', 2122, 'Marque 9');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00010', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8', 'Fournisseur 10', 2324, 'Marque 10');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00011', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 11', 2526, 'Marque 11');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00012', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 12', 2728, 'Marque 12');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00013', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 13', 2930, 'Marque 13');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00014', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 14', 3132, 'Marque 14');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00015', 2, 3, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 15', 3334, 'Marque 15');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00016', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 16', 3536, 'Marque 16');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00017', 2, 3, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 17', 3738, 'Marque 17');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00018', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 18', 3940, 'Marque 18');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00019', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 19', 4142, 'Marque 19');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00020', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8', 'Fournisseur 20', 4344, 'Marque 20');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00021', 3, 1, 1, 'SZDTYVDXZUDXZ8', 'AZERTY5R6FS6', 'Fournisseur 21', 4546, 'Toshiba');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00022', 4, 4, 1, '243546DFZ676UH', 'AZERTY5R6FS6', 'Fournisseur 22', 4748, 'Toshiba');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande, fournisseur, code_fournisseur, marque) VALUES ('00023', 4, 1, 2, '243546DFZ676UH', 'AZERTY5R6FS6', 'Fournisseur 23', 4950, 'Toshiba');