INSERT INTO zone (nom) VALUES ('Ecole');
INSERT INTO zone (nom) VALUES ('Logements');
INSERT INTO batiment (nom, id_zone) VALUES ('Bat A', 1);
INSERT INTO batiment (nom, id_zone) VALUES ('Bat B', 1);
INSERT INTO batiment (nom, id_zone) VALUES ('Bat C', 1);
INSERT INTO batiment (nom, id_zone) VALUES ('Bat P', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('1', 1);
INSERT INTO etage (nom, id_batiment) VALUES ('2', 1);
INSERT INTO etage (nom, id_batiment) VALUES ('3', 1);
INSERT INTO etage (nom, id_batiment) VALUES ('1', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('2', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('3', 2);
INSERT INTO etage (nom, id_batiment) VALUES ('-1', 3);
INSERT INTO etage (nom, id_batiment) VALUES ('Rez-de-chaussée', 3);
INSERT INTO etage (nom, id_batiment) VALUES ('1', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A100', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A101', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A102', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A103', 1);
INSERT INTO piece (nom, id_etage) VALUES ('A200', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A201', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A202', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A203', 2);
INSERT INTO piece (nom, id_etage) VALUES ('A300', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A301', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A302', 3);
INSERT INTO piece (nom, id_etage) VALUES ('A303', 3);
INSERT INTO piece (nom, id_etage) VALUES ('B100', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B101', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B102', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B103', 4);
INSERT INTO piece (nom, id_etage) VALUES ('B200', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B201', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B202', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B203', 5);
INSERT INTO piece (nom, id_etage) VALUES ('B300', 6);
INSERT INTO piece (nom, id_etage) VALUES ('B301', 6);
INSERT INTO piece (nom, id_etage) VALUES ('B302', 6);
INSERT INTO piece (nom, id_etage) VALUES ('B303', 6);
INSERT INTO piece (nom, id_etage) VALUES ('C-100', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C-101', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C-102', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C-103', 7);
INSERT INTO piece (nom, id_etage) VALUES ('C000', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C001', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C002', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C003', 8);
INSERT INTO piece (nom, id_etage) VALUES ('C100', 9);
INSERT INTO piece (nom, id_etage) VALUES ('C101', 9);
INSERT INTO piece (nom, id_etage) VALUES ('C102', 9);
INSERT INTO piece (nom, id_etage) VALUES ('C103', 9);
INSERT INTO categorie (nom) VALUES ('Chaise');
INSERT INTO categorie (nom) VALUES ('Table');
INSERT INTO categorie (nom) VALUES ('PC portable');
INSERT INTO categorie (nom) VALUES ('Vidéo projecteur');
INSERT INTO etat (nom) VALUES ('Neuf');
INSERT INTO etat (nom) VALUES ('Bon état');
INSERT INTO etat (nom) VALUES ('Mauvais état');
INSERT INTO etat (nom) VALUES ('En attente de destruction');
INSERT INTO etat (nom) VALUES ('Détruit');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00001', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00002', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00003', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00004', 1, 1, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00005', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00006', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00007', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00008', 1, 5, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00009', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00010', 1, 2, 1, 'FUDGZ67328EYGH', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00011', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00012', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00013', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00014', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00015', 2, 3, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00016', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00017', 2, 3, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00018', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00019', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00020', 2, 1, 1, '6UTDGE7GFCHECF', 'HTDF6T673DG8');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00021', 3, 1, 1, 'SZDTYVDXZUDXZ8', 'AZERTY5R6FS6');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00022', 4, 4, 1, '243546DFZ676UH', 'AZERTY5R6FS6');
INSERT INTO article (num_inventaire, categorie, etat, id_piece, num_serie, num_bon_commande) VALUES ('00023', 4, 1, 2, '243546DFZ676UH', 'AZERTY5R6FS6');