version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./IMTVENTAIRE:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3333
      - HOST=0.0.0.0
      - DB_CONNECTION=pg
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB_NAME=imtventaire
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imtventaire
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./IMTVENTAIRE/database/insert_table.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
      - ./IMTVENTAIRE/database/insert_data.sql:/docker-entrypoint-initdb.d/02-insert-data.sql

volumes:
  postgres_data: 